function Tdebug = afegeixDebugBloc( ...
    Tdebug, bucle, ...
    nP, inP_ini, ...
    nT, nR, nSlots, nMinsTot, ...
    tipus, ...
    nDies, dies_x_programacio, ...
    nHosp, nUrg, ...
    dies_procediments, ...
    lastID, maxID, nP_total, Total_Files, Total_Dies, ...
    lastMilp, default_inP, comment)
% Afegeix una fila de debug corresponent a un bloc MILP
% Cada fila està identificada pel número de bloc (bucle)

    %% Autoinicialització Tdebug (primer cop)
    if isempty(Tdebug)
        Tdebug = table( ...
            'Size', [0 31], ...
            'VariableTypes', { ...
                'double', ...   % bloc
                'double', ...   % nP
                'double', ...   % inP_ini
                'double', ...   % inP_fi
                'double', ...   % nT
                'double', ...   % nR
                'double', ...   % nSlots
                'double', ...   % nMinsTot
                'double', ...   % nGastro
                'double', ...   % nColono
                'double', ...   % nOtros
                'double', ...   % nDies
                'double', ...   % nDiesReal
                'datetime', ... % diaIni_prog
                'datetime', ... % diaFi_prog
                'string', ...   % dies_x_programacio
                'double', ...   % nHosp
                'double', ...   % nUrg
                'double', ...   % nNoConsiderats
                'double', ...   % nDies_procediments
                'datetime', ... % diaIni_procediments
                'datetime', ... % diaFi_procediments
                'string', ...   % dies_procediments
                'double', ...   % lastID
                'double', ...   % maxID
                'double', ...   % nP_total
                'double', ...   % Total_Files
                'double', ...   % Total_Dies
                'logical', ...  % lastMilp
                'double',...    % default_inP
                'string' ...    % comment
            }, ...
            'VariableNames', { ...
                'bloc', 'nP', 'inP_ini', 'inP_fi', ...
                'nT', 'nR', 'nSlots', 'nMinsTot', ...
                'nGastro', 'nColono', 'nOtros', ...
                'nDies', 'nDiesReal', ...
                'diaIni_prog', 'diaFi_prog', 'dies_x_programacio', ...
                'nHosp', 'nUrg', 'nNoConsiderats', ...
                'nDies_procediments', 'diaIni_procediments', ...
                'diaFi_procediments', 'dies_procediments', ...
                'lastID', 'maxID', 'nP_total', 'Total_Files', 'Total_Dies', ...
                'lastMilp', 'default_inP', 'comment' ...
            });
    end

    % Forçar tipus
    lastMilp = logical(lastMilp);
    if ~isstring(comment), comment = string(comment); end

    %% Comptatge tipus de procediment
    nGastro = sum(tipus == "Gastroscopia");
    nColono = sum(tipus == "Colonoscopia");
    nOtros  = sum(tipus == "Otros");

    %% Dies per programació
    if isempty(dies_x_programacio)
        diaIni_prog = NaT;
        diaFi_prog  = NaT;
        nDiesReal   = 0;
        diesProgStr = "";
    else
        diaIni_prog = dies_x_programacio(1);
        diaFi_prog  = dies_x_programacio(end);
        nDiesReal   = numel(dies_x_programacio);

        fmt = 'yyyy-MM-dd';
        diesProgStr = strjoin(string(dies_x_programacio, fmt), ", ");
    end

    %% Dies dels procediments (mateix tractament)
    if isempty(dies_procediments)
        diaIni_proc = NaT;
        diaFi_proc  = NaT;
        nDies_proc  = 0;
        diesProcStr = "";
    else
        diaIni_proc = dies_procediments(1);
        diaFi_proc  = dies_procediments(end);
        nDies_proc  = numel(dies_procediments);

        fmt = 'yyyy-MM-dd';
        diesProcStr = strjoin(string(dies_procediments, fmt), ", ");
    end

    %% Crear nova fila
    novaFila = table( ...
        bucle, ...
        nP, ...
        inP_ini, ...
        inP_ini + nP - 1, ...
        nT, nR, nSlots, nMinsTot, ...
        nGastro, nColono, nOtros, ...
        nDies, nDiesReal, ...
        diaIni_prog, diaFi_prog, diesProgStr, ...
        nHosp, nUrg, nHosp + nUrg, ...
        nDies_proc, diaIni_proc, diaFi_proc, diesProcStr, ...
        lastID, maxID, nP_total, Total_Files, Total_Dies, ...
        lastMilp, default_inP, comment, ...
        'VariableNames', Tdebug.Properties.VariableNames);

    %% Afegir fila
    Tdebug = [Tdebug; novaFila];
end